#!/usr/bin/env python3

import sys


#these are alignments generated from the Python_04.fasta file made in ClustalW. These are stored in the PFB2017_problemsets/pythonfiles/

seq_1='''>gi|170746|gb|M12277.1|WHTH4091
--------------------------------------------------
-----------------------------------AGCACCCTCCCACCT
CATCCCACCCTTCTGATCTCAATCCAACGTCGCATCTCCAC-CGTCTCGC
GGA----TCGACCCAGCGAAGTCCCTC----CCGCCCCCAAAGTCCCCCA
AATCTTGCAGTTCCCTCCTAAATCCTCCCCA------------TATAAAC
CAACCCCCCGCCCTCAGATCCC-TAATCCCATCGCAAGCA--TCAGACTC
CCTCCAAAGCAGGCAGCAGCTCCTCTTCTTCCTAATCACACTATCTCGGA
GAGGAGCGGCCATGTCTGGGCGCGACAAGGGCGGCAAGGGGCTGGGCAAG
GGCGGCGCCAAGCGGCACCGGAAGGTCCTCCGCGACAACATCCAGGGCAT
CACCAAGCCGGCGATCCGGAGGCTGGCCAGGAGGGGCGGCGTGAAGCGCA
TCTCCGGCCTCATCTACGAGGAGACCCGCGGCGTCCTCAAGATCTTCCTC
GAGAACGTCATCCGCGACGCCGTCACCTACACCGAGCACGCCCGCCGCAA
AACCGTCACCGCCATGGACGTCGTCTACGCGCTCAAGCGCCAGGGCCGCA
CCCTCTACGGCTTCGGAGGCTAGATTTGTGTGGTGAAGCAACTTCCTCGT
TTGCTCTGTGATCTGTGCT---GTCGTAGATGAGATTTACTGATTTGGCG
TGCGCCGGTTGTATTCTGTCA-TGGGGTTCAGTGGGCTGTGTAATACCTT
GCTCTGTACTTCTGTTCAATGCAATCACTTCT---ATTCTGAA-------
------------------------------'''

print(seq_1)

seq_2='''>gi|603555|emb|X83548.1|
TCTAGAGATGGCGCCATTTGATTCCAGCAGCCACAAAGCACTAGAACAAT
CGATGCTAAGAGGTGACAGGAAAAACAGGCTGCAAAGACCCAGACAATGG
AATGCAGCGGTGGTCAGCCTAAAACACTGTAGAAGGGCAAGATGAGCTGA
GTAATTTTTAACTGGGCATCATTTTTAGAAACTGGAGTTTAAGTACCCCC
--TTTTCCATTTTTTCCTGAAGTCGTGGGCAGGGCGCAAGGTCTGTGAAT
CGGCCGACCGGATGCAGCTGGTGTGGAGAGTTCCCAATCAGGTCCGATTT
ATTACTATATAAAGTACTGCTGCGAGGCTTGCCG--TGTTGCATTTTGTT
TAGTACAAGACATGTCTGGGCGCGGCAAAGGCGGGAAGGGTCTGGGCAAA
GGAGGCGCTAAGCGCCACCGCAAAGTTCTGCGCGACAACATTCAGGGCAT
CACCAAGCCCGCCATCCGACGCCTGGCACGGCGTGGAGGCGTTAAGCGCA
TCTCAGGCCTTATATACGAGGAGACACGCGGAGTTCTTAAAGTGTTTTTG
GAGAATGTAATCCGCGATGCAGTTACCTACACGGAGCACGCCAAACGCAA
GACAGTCACAGCCATGGACGTGGTTTACGCGCTCAAGCGCCAGGGCCGCA
CCCTGTATGGCTTTGGCGGC------TGAGTGTTTTACTTACTTACACGG
TTCCTCAAAGGCCCTTCTCAGGGCCACCCATGAAGTCTGTGAAAGAGCTG
TAGACTAAAGATAGTTAATTTCTTAAGAACACTTAAACGTATGGCAGTTT
TGGCAAATTAGCGATTCCACATAAGCAGTCGCTGAAGTTTGAGGTTCGGT
GCCCCTTTCAGCATTACTTAGTGGTTAAAA'''


seq_1=seq_1.replace('\n','')#strip \n from the middle of things will not work.

seq_2=seq_2.replace('\n','')

print(seq_2)
